### ISSUE TITLE
Kibana and Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by dignajar** [opendistro-for-elasticsearch/community#101]
Hi,
it's possible to use `Open Distro for Elasticsearch Kibana` and `Amazon Elasticsearch Service` ?

I set via environment variable `ELASTICSEARCH_URL` and `ELASTICSEARCH_HOSTS` with the endpoint from AWS Elasticsearch Service, `https://<es-endpoint>:443` and I have some logs about authentication.

```
{"type":"log","@timestamp":"2019-07-25T08:47:08Z","tags":["status","plugin:elasticsearch@undefined","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Authorization Exception","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
```

**Comment by aetter** [comment]
Hi @dignajar, so I believe you *can*, but the difference in plugins will cause problems. Each Kibana plugin needs its corresponding Elasticsearch plugin to work properly.

For example, if you have a self-hosted Kibana install that uses the alerting plugin and shares the exact same version, you *might* be able to use it with an Amazon ES domain, because Amazon ES domains include the Elasticsearch alerting plugin. I haven't tested, so I have to say "might." :)

If your Kibana install uses the security plugin, though, you won't be able to connect, because Amazon ES domains don't have the corresponding security plugin. That's the authentication issue you're running into.

Of course, Amazon ES domains come with a preinstalled version of Kibana that shares the same version and has all the plugins you need, so the utility of hooking up a self-hosted Kibana install is a little questionable. Even if it can be done, I wouldn't really recommend it.

**Comment by dignajar** [comment]
Thank you @aetter for your answer.
We were looking for a Kibana with more steroid than the Kibana from AWS.

**Comment by danopia** [comment]
To provide a data point, I've been using OpenDistro Kibana (most recently 0.9.0) with my AWS ES clusters for many months now. I self-host a Kibana in order to:

- use a vanity domain name with HTTPS
- access Kibana at the domain root, not `/_plugin/kibana`
- access a VPC Cluster's Kibana through an Internet-facing ALB
- leverage an org-internal web auth config

To do this, you have to make a variant of the Kibana docker image with opendistro_security removed. I also added a `abutaha/aws-es-proxy` sidecar so Kibana can access the cluster APIs by just hitting http://localhost:9200.

The only problem I've noticed thus far is in creating Alerting triggers, there's some JS crash: `TypeError: Cannot read property 'thresholds' of undefined`. I haven't been able to fully configure alerts through the built-in AWS ES Kibana either so not really much of a loss to me.
