### ISSUE TITLE
Managed Service

### ISSUE THREAD

**Issue by gruebel** [opendistro-for-elasticsearch/community#15]
Hi,

do you have any plans to add the new functionality to the existing AWS Elasticsearch Service or offer a new managed service with all these features? Would love to see the security addtions to be added!

**Comment by CarlMeadows** [comment]
Hi Gruebel - With my AWS hat on - we do plan on offering these features on Amazon Elasticsearch Service. We wanted to make them available on Open Distro for Elasticsearch prior to adding them to service so that the community and customers could benefit and participate in the productization. I can't comment on the specific timelines - but our investment in the Security side was born out of that being a hugely popular request from our customers and it is a very high priority for us. Thanks!
