### ISSUE TITLE
Where is the fork source code

### ISSUE THREAD

**Issue by DBarthe** [opendistro-for-elasticsearch/community#21]
Hello,

It is not clear to me where does the actual source code of the elasticsearch fork live. 
It seems that there is no such repository in the "opendistro-for-elasticsearch" github org. Do I missed something ?

**Comment by CarlMeadows** [comment]
Hi. 

We are currently building directly on the Apache OSS binaries for Elasticsearch and Kibana. So we don't publish our version of source as we are not doing our own build. Doing our own build (and publishing our version of the source) will be a requirement in order to apply our own compile time patches to the core - which seems like it will be needed, but this is also why we have been claiming it is not a fork - even though that doesn't seem to be the most believed point in our messaging :)

**Comment by DBarthe** [comment]
Thank you for the explanation. So at the moment it is just an elasticsearch-oss bundled with some convenient plugins I could otherwise install myself on my existing clusters, right ?

**Comment by CarlMeadows** [comment]
Correct - we build the distro by building each component and packaging with the OSS versions of Elasticsearch and Kibana - you can do the same and load them onto your existing version of Elasticsearch and Kibana assuming it is a compatible version. We are working on getting all of the documentation and artifacts organized to make that easy.
