### ISSUE TITLE
Release/Branch version inconsistent?

### ISSUE THREAD

**Issue by tremmert** [opendistro-for-elasticsearch/community#42]
The branches in github for the minor release are all 0.7.0.1 while the docker images as per documentation https://opendistro.github.io/for-elasticsearch-docs/ are 0.7.1 .. e.g. docker pull amazon/opendistro-for-elasticsearch-kibana:0.7.1

Is that on purpose?

**Comment by CarlMeadows** [comment]
We had originally been planning on using a 4 digit numbering convention that would align like this:
first digit - aligns with ES major verisons
second digit - aligns with ES minor versions
third digit - minor feature enhancements with Open Distro but same ES version
forth digit - out of band critical patches

The fix for the yellow cluster bug in the security config qualified as a out of band critical patch - however as we have been getting everything setup it has been raised that NPM only supports 3 digits so we are likely going to have to collapse the 3rd and 4th digits just so we dont create consistency issues and confusion between plugins which use Maven (ES Plug-ins) and those that use NPM (Kibana).

Does that make sense?
